# SonarCloud required
sonar.projectKey=aijazkhan123_devsecops-project
sonar.organization=aijazkhan123
sonar.host.url=https://sonarcloud.io

# Project details
sonar.projectName=DevSecOps Project
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
